ECHO -----------   UPGRADE pip   -----------
python -m pip install --upgrade pip
ECHO -----------   xlrd   --------------
pip install xlrd
ECHO -----------   xlutils   --------------
pip install xlutils
ECHO -----------   numpy   --------------
pip install numpy
ECHO -----------   pandas   --------------
pip install pandas
ECHO -----------   openpyxl   --------------
pip install openpyxl
ECHO -----------   PyPDF2   --------------
pip install PyPDF2
ECHO -----------   reportlab   --------------
pip install reportlab
ECHO -----------   flask   --------------
pip install flask
ECHO -----------   FIN   --------------

